### ISSUE TITLE
Updates needed to comply with the new NSF NCAR branding and style

### ISSUE THREAD

**Issue by erogluorhan** [NCAR/jekyll-koru#16]
This theme needs to be updated to address the changes in the recent [branding updates](https://sundog.ucar.edu/page/7480#For-materials-relate-13)

**Comment by geinosky** [comment]
This is complete and is available in the latest release: https://github.com/NCAR/koru-jekyll/releases/tag/1.0.42 To update in your site go to the _config.yml file and update to `remote_theme: ncar/koru-jekyll@1.0.42`

**Comment by erogluorhan** [comment]
Thanks very much for this! Created a PR to update to it; once it shows up, I'll close this
